### PR TITLE
Fix the migration script

### PR DESCRIPTION
**Pull request by llucax**
The `*` needs to be escaped in the sed command as it has a special meaning.

### CODE REVIEW

**Comment by llucax** [comment]
Skipping release notes because it fixes an unreleased feature.

**Comment by Marenz** [comment]
CI needs appeasing

**Comment by llucax** [comment]
`git commit -a` :boom: 

Will fix.

**Comment by llucax** [comment]
Updated

**Review by Marenz — APPROVED** [review]

**Pull request merged**
